version: '3.8'

services:
  user:
    build: .
    container_name: SaaS-user
    ports:
      - "82:8080"
    volumes:
      - ./src:/app/src
    external_links:
      - pay-db:db
    networks:
      - saas-network

  nginx:
    build: ./nginx
    container_name: user-nginx
    ports:
      - "92:90"
    depends_on:
      - user
    networks:
      - saas-network

volumes:
  mysql:

networks:
  saas-network:
    driver: bridge
